### ISSUE TITLE
CI: Cache downloaded pre-trained models

### ISSUE THREAD

**Issue by pjbull** [drivendataorg/zamba#90]
We should try to cache the pretrained models in addition to the requirements.

Some considerations: 
 - Cache can only be 5GB, so between these and the reqs we might not actually get any benefit
 - Download is _very_ fast on ubuntu and probably won't speed up CI runs there; will potentially speed up windows and macos
 - We should be able to get the folder like we do for pip with something like:

```yaml
    - name: Get model cache dir
      id: model-cache
      shell: bash -l {0}
      run: |
        echo "::set-output name=dir::$(python -c 'import zamba;print(zamba.config.cache_dir)')"
```
